"""Unified file conversion interface."""

from enum import Enum
import logging
from pathlib import Path
from typing import Protocol

logger = logging.getLogger(__name__)


class ConversionFormat(str, Enum):
    """Supported conversion formats."""

    TXT = "txt"
    PDF = "pdf"
    PNG = "png"
    HTML = "html"
    MD_NO_TABLE = "md_no_table"  # Markdown with tables removed


class Converter(Protocol):
    """Converter protocol."""

    def convert(
        self,
        input_path: Path,
        output_path: Path | None = None,
        **options,
    ) -> Path:
        """Run the conversion and return the output file path."""
        ...


def get_converter(
    source_format: str,
    target_format: ConversionFormat,
) -> Converter:
    """Return the appropriate converter based on source and target formats."""
    source = source_format.lower().lstrip(".")

    if target_format == ConversionFormat.TXT:
        if source in ("md", "markdown"):
            from b2t.converter.md_to_txt import MarkdownToTextConverter

            return MarkdownToTextConverter()

    if target_format == ConversionFormat.PDF:
        if source in ("md", "markdown"):
            from b2t.converter.md_to_pdf import MarkdownToPdfConverter

            return MarkdownToPdfConverter()

    if target_format == ConversionFormat.PNG:
        if source in ("md", "markdown"):
            from b2t.converter.md_to_png import MarkdownToPngConverter

            return MarkdownToPngConverter()
        if source == "html":
            from b2t.converter.md_to_png import HtmlToPngConverter

            return HtmlToPngConverter()

    if target_format == ConversionFormat.HTML:
        if source in ("md", "markdown"):
            from b2t.converter.md_to_html import MarkdownToHtmlConverter

            return MarkdownToHtmlConverter()

    if target_format == ConversionFormat.MD_NO_TABLE:
        if source in ("md", "markdown"):
            from b2t.converter.md_remove_table import MarkdownRemoveTableConverter

            return MarkdownRemoveTableConverter()

    raise ValueError(f"Unsupported conversion: {source} -> {target_format.value}")


def convert_file(
    input_path: Path | str,
    target_format: ConversionFormat,
    output_path: Path | str | None = None,
    **options,
) -> Path:
    """
    Universal file conversion function.

    Args:
        input_path: Input file path
        target_format: Target format
        output_path: Output file path (optional, auto-generated by default)
        **options: Extra options passed to the converter

    Returns:
        Output file path
    """
    input_path = Path(input_path)
    if not input_path.exists():
        raise FileNotFoundError(f"Input file does not exist: {input_path}")

    source_format = input_path.suffix
    converter = get_converter(source_format, target_format)

    if output_path is not None:
        output_path = Path(output_path)

    return converter.convert(input_path, output_path, **options)
